### ISSUE TITLE
verdi quicksetup crashes

### ISSUE THREAD

**Issue by oschuett** [aiidateam/aiida_core#572]
Running 
```
$ verdi quicksetup --email some.body@xyz.com --first-name Some --last-name Body --institution XYZ
```
results in
```
Traceback (most recent call last):
  File "/software/anaconda/bin/verdi", line 9, in <module>
    sys.exit(run())
  File "/software/anaconda/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1204, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/software/anaconda/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1190, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/software/anaconda/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 631, in run
    self._quicksetup_cmd.invoke(ctx)
  File "/software/anaconda/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/software/anaconda/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/software/anaconda/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/software/anaconda/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 814, in _quicksetup_cmd
    setup(profile_name, only_config=False, non_interactive=True, **setup_args)
  File "/software/anaconda/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 601, in setup
    User().user_configure(
AttributeError: 'User' object has no attribute 'user_configure'
```

This seems to be caused by commit https://github.com/aiidateam/aiida_core/commit/28aca8cc7919abd497bf729c0cb0354161663886 .

**Comment by muhrin** [comment]
Sorry Olle.  Fixed in 771f9f66aad2df921a74f205b8fd0af693585e14.

Thanks for the useful bug report.
