### ISSUE TITLE
Structure rest-api not working in aiida 1.0.0a2

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida_core#1763]
E.g. `http://127.0.0.1:5000/api/v2/structures/b17aa1f7-025c-4b22-b6e0-dd31cf272cde/content/visualization?visformat=xsf` returns

`{"message":"Internal server error. The original message was: \"cannot import name create_node_id_qb\""}`

**Comment by waychal** [comment]
After testing, 
http://127.0.0.1:5000/api/v2/structures/60641cea/content/visualization?visformat=xsf (works fine)
http://127.0.0.1:5000/api/v2/structures/60641cea/content/visualization (gives error as visformat is passed as an None)
Fixed.

**Comment by sphuber** [comment]
Fixed in PR #2305
